name: flutter_macos_webview_example
description: Demonstrates how to use the flutter_macos_webview plugin.
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_macos_webview:
    path: ../

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
